mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: '12345'

ruby:
  build: .
  volumes:
    - .:/app
    - ~/.pry_history:/root/.pry_history
    - ~/.mysql_history:/root/.mysql_history
  links:
    - mysql
